Repository skatch-devocean-young/backend, pull requests merged in 2024-08, with the labels that each got.

#2 [Feat] : 엔터티 & 레포지토리 세팅
  build.gradle
  src/main/java/devocean/tickit/domain/Attendee.java
  src/main/java/devocean/tickit/domain/Event.java
  src/main/java/devocean/tickit/domain/EventHash.java
  src/main/java/devocean/tickit/domain/EventImg.java
  src/main/java/devocean/tickit/domain/EventInfo.java
  src/main/java/devocean/tickit/domain/EventPlace.java
  src/main/java/devocean/tickit/domain/EventTicket.java
  src/main/java/devocean/tickit/domain/Hash.java
  src/main/java/devocean/tickit/domain/Host.java
  src/main/java/devocean/tickit/domain/QrImg.java
  src/main/java/devocean/tickit/domain/Star.java
  src/main/java/devocean/tickit/domain/Ticket.java
  src/main/java/devocean/tickit/domain/User.java
  src/main/java/devocean/tickit/domain/UserInfo.java
  src/main/java/devocean/tickit/global/BaseEntity.java
  src/main/java/devocean/tickit/global/constant/ProgressStatus.java
  src/main/java/devocean/tickit/global/constant/RegisterStatus.java
  src/main/java/devocean/tickit/global/constant/Registration.java
  src/main/java/devocean/tickit/global/constant/Role.java
  src/main/java/devocean/tickit/global/constant/TicketStatus.java
  src/main/java/devocean/tickit/repository/AttendeeRepository.java
  src/main/java/devocean/tickit/repository/EventHashRepository.java
  src/main/java/devocean/tickit/repository/EventImgRepository.java
  src/main/java/devocean/tickit/repository/EventInfoRepository.java
  src/main/java/devocean/tickit/repository/EventPlaceRepository.java
  src/main/java/devocean/tickit/repository/EventRepository.java
  src/main/java/devocean/tickit/repository/EventTicketRepository.java
  src/main/java/devocean/tickit/repository/HashRepository.java
  src/main/java/devocean/tickit/repository/HostRepository.java
  src/main/java/devocean/tickit/repository/QrImgRepository.java
  src/main/java/devocean/tickit/repository/StarRepository.java
  src/main/java/devocean/tickit/repository/TicketRepository.java
  src/main/java/devocean/tickit/repository/UserInfoRepository.java
  src/main/java/devocean/tickit/repository/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 🚀 feat, 😵‍💫 sangho

#6 #3 SecurityConfig 생성
  src/main/java/devocean/tickit/global/config/SecurityConfig.java
Labels: 🚀 feat, 😇 ganghee

#10 Feature/#9/common response setting
  build.gradle
  src/main/java/devocean/tickit/global/api/ApiResponse.java
  src/main/java/devocean/tickit/global/api/CustomException.java
  src/main/java/devocean/tickit/global/api/ErrorCode.java
  src/main/java/devocean/tickit/global/api/ExceptionDto.java
  src/main/java/devocean/tickit/global/api/GlobalExceptionHandler.java
  src/main/java/devocean/tickit/global/api/ResponseStatusCodeSetterAdvice.java
Labels: 🚀 feat, 😇 ganghee

#14 [chore] : 블루-그린 무중단 배포 설정
  Dockerfile
  src/main/resources/application.yml
Labels: 🚀 feat, ⚒️ chore, 😵‍💫 sangho

#17 Feature/#4/filter setting
  src/main/java/devocean/tickit/controller/TestController.java
  src/main/java/devocean/tickit/dto/TestLogInRequestDto.java
  src/main/java/devocean/tickit/dto/TestSignInRequestDto.java
  src/main/java/devocean/tickit/global/SecurityConfig.java
  src/main/java/devocean/tickit/global/api/ErrorCode.java
  src/main/java/devocean/tickit/global/api/GlobalExceptionHandler.java
  src/main/java/devocean/tickit/global/jwt/JwtFilter.java
  src/main/java/devocean/tickit/global/jwt/JwtUtils.java
  src/main/java/devocean/tickit/service/AuthenticationService.java
  src/main/java/devocean/tickit/service/TestService.java
  src/main/resources/application.yml
Labels: 🚀 feat, 🚨 fix, ⚒️ chore, 😇 ganghee

#18 [fix] : security config 수정
  src/main/java/devocean/tickit/controller/TestController.java
  src/main/java/devocean/tickit/global/SecurityConfig.java
  src/main/java/devocean/tickit/global/config/SecurityConfig.java
Labels: 🚨 fix, 🔄 refactor, ⚒️ chore, 😵‍💫 sangho

#19 [fix] : jwt filter 세팅
  src/main/java/devocean/tickit/global/config/SecurityConfig.java
Labels: 🚨 fix, 😇 ganghee
